Integrate Standard Guidelines into Client
Cyber4All/CLARK-Gateway pull request #167
Opened 2021-08-13 16:09 UTC by Cwagne17

PR completes requirement # 1 of [Story 5026](https://app.clubhouse.io/clarkcan/story/5026/integrate-standard-guidelines-into-client). 

```
1. Add proxy to standard guidelines search routes in clark-gateway.
```

It adds the proxy to route to standard-guidelines-service
As well as adds complete documentation for the swagger docs

2021-08-13 16:29 UTC, mfranz1 approved these changes

2021-08-16 12:38 UTC, EVogel1999 requested changes
Looks good!  I just have one suggestion for the routes.  The 200s cases should reference a component schema if it returns a framework(s), guideline(s), or search index(es).

Edit: Make sure you whitelist GET /frameworks and GET /guidelines

2021-08-16 12:38 UTC, EVogel1999 commented on src/modules/standard-guidelines/auth-module/AuthController.ts
> +         *        description: FORBIDDEN - User is not whitelisted, please use a whitelisted certificate
It doesn't throw these at all with this route, only with the routes that require authentication.  It returns an optional token (if they have the cert) and redirects them to the standard guidelines client regardless if they are authenticated or not.

2021-08-16 12:38 UTC, EVogel1999 commented on src/modules/standard-guidelines/framework-module/FrameworkController.ts
> +         *        description: OK
Can we get a component schema for framework?

2021-08-16 12:38 UTC, EVogel1999 commented on src/modules/standard-guidelines/guideline-module/GuidelineController.ts
> +         *        description: OK
Can we also get a component schema for guidelines?

2021-08-16 12:38 UTC, EVogel1999 commented on src/modules/standard-guidelines/guideline-module/GuidelineController.ts
> +         *        description: OK
Same here.

2021-08-16 12:38 UTC, EVogel1999 commented on src/modules/standard-guidelines/search-module/SearchController.ts
> +         *        description: OK
This should reference the framework component schema.

2021-08-16 12:38 UTC, EVogel1999 commented on src/modules/standard-guidelines/search-module/SearchController.ts
> +         *        description: OK
This should have a search index component schema in references.

2021-08-16 13:51 UTC, pzalep1 reviewed
Once Emily's comments are addressed this will be good to go.

2021-08-16 17:28 UTC, jouypo23 approved these changes

2021-08-16 19:14 UTC, pzalep1 approved these changes

2021-08-16 19:36 UTC, EVogel1999 approved these changes
Looks good!  Thank you for the schemas.

2021-08-17 13:20 UTC, merged