feat: New orb applied to deployment pipeline
Cyber4All/CLARK-Gateway pull request #214
Opened 2022-05-13 14:52 UTC by Cwagne17

This PR will merge the orb changes into releases which will then run the deployment-production pipeline

2022-05-16 13:49 UTC, mfranz1 requested changes

2022-05-16 13:49 UTC, mfranz1 commented on .circleci/config.yml
> +  cyber4all: cyber4all/orb@1.0.4
```suggestion
  cyber4all: cyber4all/orb@1.0
```

2022-05-16 14:12 UTC, mfranz1 submitted a review, later dismissed

2022-05-16 14:19 UTC, StarChaser44 approved these changes

2022-05-16 14:42 UTC, pmanal1 approved these changes

2022-05-26 12:00 UTC, JosueMolinaMorales submitted a review, later dismissed

2022-06-02 16:10 UTC, pzalep1 approved these changes

2022-06-02 16:10 UTC, pmanal1 approved these changes

2022-06-02 16:11 UTC, merged