Feature/sc-27984/implement-getting-reviewers-or-curators-for
Cyber4All/CLARK-Gateway pull request #349
Opened 2024-02-05 23:10 UTC by bereketsega

2024-02-06 14:26 UTC, mfranz1 approved these changes

2024-02-07 20:42 UTC, Cwagne17 requested changes

2024-02-07 20:42 UTC, Cwagne17 commented on src/modules/clark/access-group-module/access-group.routes.ts
>          target: envConfig.getUri(USER_SERVICE_URI),
```suggestion
```

We should remove the target because it'll point to clark-service now.

2024-02-07 21:08 UTC, Cwagne17 approved these changes

2024-02-09 14:13 UTC, JosueMolinaMorales approved these changes

2024-02-09 15:38 UTC, shanioffe approved these changes

2024-02-12 14:27 UTC, merged