Feature/sc 32286/implement getting a learning object parent
Cyber4All/CLARK-Gateway pull request #394
Opened 2024-07-18 19:31 UTC by curlyLasagna

Gateway route for getting a learning object's parent

https://app.shortcut.com/clarkcan/story/32286/implement-getting-a-learning-object-parent-in-clark-service

2024-07-18 20:52 UTC, Greek approved these changes

2024-07-19 11:24 UTC, stef359 approved these changes

2024-07-22 02:50 UTC, pzalep1 approved these changes

2024-07-22 14:39 UTC, mfranz1 requested changes

2024-07-22 14:39 UTC, mfranz1 commented on src/modules/clark/learning-object-module/learning-objects.routes.ts
> +        path: "/learning-objects/:id/parents",
```suggestion
        path: "/learning-objects/:learningObjectId/parents",
```

2024-07-22 15:19 UTC, mfranz1 approved these changes

2024-07-22 15:19 UTC, merged