Feature/sc 34538/add card service to clark gateway
Cyber4All/CLARK-Gateway pull request #407
Opened 2024-10-28 17:29 UTC by Cwagne17

Adds card service routes to the Gateway (does not include user module because cards-client is going to use clark anyways.

2024-10-29 18:04 UTC, pzalep1 approved these changes

2024-10-30 16:25 UTC, stef359 approved these changes

2024-10-30 17:04 UTC, dsoto18 approved these changes

2024-10-30 17:10 UTC, Greek requested changes

2024-10-30 17:10 UTC, Greek commented on src/modules/card/search/search.router.ts
> +        console.log('SearchRouteHandler.build()');
```suggestion
```

2024-10-31 14:18 UTC, johngonz0 approved these changes

2024-10-31 17:46 UTC, Greek approved these changes

2024-10-31 17:51 UTC, merged